version: '3.8'

services:
  db:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - /home/pedro/volumes-docker/api-dd:/data/db