version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    container_name: api-dd
    volumes:
      - .:/volume
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/api-dd
      - SECRET_JWT=hX3a2Df5Kr8zLj9pT4wQm1Vc6GyN7vXe
    networks:
      - default
  db:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
    container_name: mongodb
    volumes:
      - .:/volume
    networks:
      - default
networks:
  default:
    driver: bridge
